# -*- coding: utf-8 -*-
"""CaseStudyCLT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JEOM5JT5ZJuz7J_a4HokluGM39YbJPUH
"""

import seaborn as sns
import pandas as pd
df = sns.load_dataset('titanic')

import seaborn as sns

# Load dataset directly from seaborn
train_df = sns.load_dataset('titanic')

# If you still need a "test" set, you’ll have to split it manually
from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(train_df, test_size=0.2, random_state=42)
train_df

df = pd.concat([train_df.drop(columns=['survived']),test_df]).sample(500)

df['fare'].plot(kind='kde')

samples = []
for i in range(100):
    samples.append(df['fare'].dropna().sample(50).values.tolist())

import numpy as np
samples = np.array(samples)

sampling_means = samples.mean(axis=1)

sns.kdeplot(sampling_means)

sampling_means.mean()

sampling_means.std()/np.sqrt(50)

lower_limit = sampling_means.mean() - 2*sampling_means.std()
upper_limit = sampling_means.mean() + 2*sampling_means.std()

print('The range is',lower_limit,'-',upper_limit)

df['fare'].dropna().mean()

